sudo: false
language: generic

os:
 - linux

python:
  - "3.6"

global:
  env:
    - COMMIT_AUTHOR_EMAIL: "f.zapata@esciencecenter.nl"

install:
  # install miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False

  # install dependencies
  - conda update conda
  - conda install -c anaconda twisted==18.4.0
  - conda install -c anaconda libgfortran
  - conda install -c openbabel openbabel
  - conda install ambertools=19 -c ambermd
  - conda install numpy

  - (git clone git://github.com/MD-Studio/MDStudio.git --single-branch && pip install -e MDStudio/mdstudio)

  # install library
  - pip install -e .[test]
  
script:
  - (cd test && coverage run -m unittest discover -vvv)

branches:
  only:
    - master

after_success:
  - codecov